node {
    def app

    stage('Clone repository') {
      

        checkout scm
    }

    stage('Update GIT') {
            script {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                        sh "git config user.email tanabat.suasawathe@gmail.com"
                        sh "git config user.name Tanabat"
                        //sh "git switch master"
                        sh "cat Deploy/deployment.yaml"
                        sh "sed -i 's+hamtaro702/test.*+hamtaro702/test:${DOCKERTAG}+g' Deploy/deployment.yaml"
                        sh "cat Deploy/deployment.yaml"
                        sh "git add ."
                        sh "git commit -m 'Done by Jenkins Job changemanifest: tag ${DOCKERTAG}'"
                        sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/test-deops.git HEAD:master"
      }
    }
  }
}
}